version: "3.8"

services:
  web:
    image: abhi25022004/django-note-app:latest
    ports:
      - "8000:8000"
    restart: always  # Auto-restart on failure
    working_dir: /app/backend  # Ensure correct working directory
    volumes:
      - .:/app/backend  # Useful for local development (optional)
    environment:
      - PYTHONUNBUFFERED=1  # Helps with logging inside containers
